### ISSUE TITLE
Do I need a .profile?

### ISSUE THREAD

**Issue by evantravers** [evantravers/dotfiles#6]
While setting up a new ARM Mac… I ran into the problem of the executables that had just been installed by `brew bundle` not being seen by fish when it's switched as the shell, and apparently some of the dependencies of my fish plugins (which have already been `stow`'d into the right folders) fail and crash without it.

I found this `.profile` file somewhere:

```sh
eval $(/opt/homebrew/bin/brew shellenv)
eval $(export HOMEBREW_PREFIX="/opt/homebrew");
export HOMEBREW_CELLAR="/opt/homebrew/Cellar";
export HOMEBREW_REPOSITORY="/opt/homebrew";
export PATH="/opt/homebrew/bin:/opt/homebrew/sbin${PATH+:$PATH}";
export MANPATH="/opt/homebrew/share/man${MANPATH+:$MANPATH}:";
export INFOPATH="/opt/homebrew/share/info:${INFOPATH:-}";
```

This appears to generally work, but it's dependent on whether it's ARM or Intel.

**Comment by evantravers** [comment]
@tbmiller and @megalithic, what do you think?

**Comment by tmiller** [comment]
Is this a problem due to you having configs pointing to the incorrect locations? I don't have this issue on my setup, because I'm using something to generate stuff based on my operating system and architecture. If you need to script it you can compare the results of `uname -p` to get your architecture.

**Comment by evantravers** [comment]
Closed by https://github.com/evantravers/dotfiles/commit/0738a5f6dc2e2ab96600fe0eb17724cc29a307b7
